  
version: '3'


volumes:
  grafana:


services:

  grafana:
    image: grafana/grafana:7.4.0
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin